package de.selenium.exception;

//Definition der Enum für Fehlertypen
public enum FehlerTyp {
 DATEI_NICHT_GEFUNDEN,
 UNGUELTIGE_EINGABE,
 VERBINDUNGSFEHLER,
 UNBEKANNTER_FEHLER,
 IMAGENICHTSichtbar,
 ElementExistiertNicht,
 UNGUELTIGE_ZEILE,
 FILE_EXISTIERT_NICHT,
 FEHLER_BEI_VERARBEITUNG_DER_DATEI,
 VALUE_EXISTIERT_NICHT,
 DER_WEBDRIVER_NICHT_VORHANDEN 

}
